[build]
  base = "faq"          # folder project astro kamu
  command = "npm run build"
  publish = "dist"      # hasil build astro ada di dist

[build.environment]
  NODE_VERSION = "22"   # 🔑 paksa Netlify pakai Node 20.x

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

