[build]
  base = "faq"          # Jika proyek Next.js berada di dalam folder "faq"
  command = "npm run build"
  publish = ".next"     # Menggunakan folder .next sebagai publikasi

[build.environment]
  NODE_VERSION = "22"   # Pastikan menggunakan Node.js 20.x

# Hapus bagian redirects yang tidak perlu
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
