[build]
  base = "faq"              # masuk dulu ke folder /faq
  command = "npm run build" # jalankan astro build di sana
  publish = "../public"     # hasil build keluar ke ../public (root/public)


[[redirects]]
  from = "/__/auth/handler"
  to = "/"
  status = 200

