[build]
  base = "faq"
  command = "npm run build"
  publish = "faq/.next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PRIVATE_STANDALONE = "false"

# Hapus plugin nextjs karena menyebabkan error
# [[plugins]]
#   package = "@netlify/plugin-nextjs"
