[build]
  base = "faq"                # jalankan perintah dari folder faq
  command = "npm run build"
  publish = "public"          # publish root/public (bukan ../public)

[[redirects]]
  from = "/__/auth/handler"
  to = "/"
  status = 200
