[build]
  base = "faq"          # Jika proyek Next.js berada di dalam folder "faq"
  command = "npm run build"
  publish = ".next"     # Atau "out" jika menggunakan Static Export

[build.environment]
  NODE_VERSION = "20"   # Pastikan menggunakan Node.js 20.x

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
