[build]
  base = "faq"          # Netlify masuk ke folder astro
  command = "npm run build"
  publish = "dist"      # Deploy hasil build astro

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
